<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VipCredoMetric.Application\VipCredoMetric.Application.csproj" />
    <ProjectReference Include="..\VipCredoMetric.Infrastructure\VipCredoMetric.Infrastructure.csproj" />
  </ItemGroup>

</Project>
